Mindful marko-web middleware
parameter1/base-cms pull request #1004
Opened 2024-11-04 16:12 UTC by B77Mills

- Add support for getAdvertisingPostByIdOrImportEntity to the api client.  
 - Update marko-web mindful service with updated middleware calls for getAdvertisingPostByIdOrImportEntity

2024-11-04 19:09 UTC, zarathustra323 requested changes

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/api-client.js
> +      type = 'post',
`type` shouldn't have a default value set

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/advertising-post-by-id-or-import-entity.js
> +const { asyncRoute } = require('@parameter1/base-cms-utils');
There only needs to be one marko web middleware... and that's this one. Rename this to `advertising-post-as-native-story.js` and then delete the `advertising-post-by-id.js`

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/advertising-post-by-id.js
> +const { get } = require('@parameter1/base-cms-object-path');
This file can be removed

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/advertising-post-by-id-or-import-entity.js
> +    const result = await service.getAdvertisingPostByIdOrImportEntity({
Rename the service method to `getAdvertisingPostAsNativeStory` and move the conversion to that method... see below.

In other words this should become
```js
const story = service.getAdvertisingPostAsNativeStory({ _id, preview: Boolean(req.query.preview), tenant });
res.marko(template, { story });
```

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/advertising-post-by-id-or-import-entity.js
> +      tenant: namespace,
The `namespace` is not the tenant in this case... the tenant is the `native-x` tenant key, e.g. `watt`, not `watt/default`

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/service.js
> +  async getAdvertisingPostByIdOrImportEntity({
Change this to `getAdvertisingPostAsNativeStory` with `_id`, `tenant` and `preview` as args. The provider can be hardset to `native-x` and the `type` hard set to `story`.

Use the `convertAdvertisingPostToNativeStory` directly in this method.

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/advertising-post-by-id-or-import-entity.js
> +    const story = service.convertAdvertisingPostToNativeStory({
this middleware should also return a 404 page is the story cannot be found.

2024-11-04 19:09 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/advertising-post-by-id-or-import-entity.js
> +    res.marko(template, { story });
There used to be handling for redirecting the page is the slug is wrong, or changes... but I don't see that happening here?

2024-11-05 21:00 UTC, zarathustra323 requested changes

2024-11-05 21:00 UTC, zarathustra323 commented on packages/mindful/api-client.js
> +      tenant = 'native-x',
Remove these defaults

2024-11-05 21:00 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/get-advertising-post-as-native-story.js
> +  provider,
Do not pass provider

2024-11-05 21:00 UTC, zarathustra323 commented on packages/mindful/marko-web/middleware/get-advertising-post-as-native-story.js
> +      provider,
No need to pass this

2024-11-05 21:00 UTC, zarathustra323 commented on packages/mindful/marko-web/service.js
> +    preview,
Remove the provider and type params.. only accept tenant

2024-11-05 21:00 UTC, zarathustra323 commented on packages/mindful/marko-web/service.js
> +      provider,
provider: 'native-x',
type: 'story'

2024-11-05 21:44 UTC, zarathustra323 approved these changes

2024-11-05 21:51 UTC, merged

2024-11-06 14:52 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add monorail/mindful package to replace with native story middleware with Mindful equivalent](https://trello.com/c/zU4rTgw1/547-add-monorail-mindful-package-to-replace-with-native-story-middleware-with-mindful-equivalent)