Add mutation to create a website schedule
parameter1/base-cms pull request #116
Opened 2021-07-20 19:17 UTC by solocommand

The logic for this is largely the same as the `quickCreateWebsiteSchedules` with three notable exceptions:
- Supports setting additional fields (custom optionId, startDate, & endDate)
- Only allows a single schedule to be created at once
- Now requires GraphQL authentication

This mutation is being added to support Allured's external publishing tool. Due to the backwards incompatible changes to authentication, this mutation is being created alongside `quickCreateWebsiteSchedules`, rather than replacing it.

![image](https://user-images.githubusercontent.com/1778222/126382660-1feae439-79fe-431d-a3b2-649a50221f45.png)

2021-07-20 19:18 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create GraphQL mutation: CreateWebsiteSchedule](https://trello.com/c/WKznJhJM/102-create-graphql-mutation-createwebsiteschedule)

2021-07-21 16:32 UTC, zarathustra323 requested changes

2021-07-21 16:32 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/website/schedule.js
> +  contentId: Int!
Change to `definitions: [CreateWebsiteScheduleDefinitionInput!]!`

and then do something like
```graphql
type CreateWebsiteScheduleDefinitionInput {
  contentId: Int!
  sectionId: Int!
  optionId: Int
  startDate: Date
  endDate: Date
}
```

2021-07-22 14:56 UTC, zarathustra323 approved these changes

2021-07-22 14:57 UTC, merged