Add mutation to modify content contact fields
parameter1/base-cms pull request #119
Opened 2021-07-20 21:37 UTC by solocommand

![image](https://user-images.githubusercontent.com/1778222/126398675-b8a29818-c26c-481a-89ce-f25811e392ef.png)

2021-07-20 21:37 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create GraphQL mutations to allow modification of company and event fields](https://trello.com/c/MNb1mVwT/101-create-graphql-mutations-to-allow-modification-of-company-and-event-fields)

2021-07-21 16:27 UTC, zarathustra323 requested changes

2021-07-21 16:27 UTC, zarathustra323 commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +      const fields = {
Remove these fields from the projection

2021-07-21 16:27 UTC, zarathustra323 commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +      return basedb.findOne('platform.Content', { _id: parseInt(id, 10) }, { projection });
Use `findById` and remove the `parseInt`

2021-07-21 16:38 UTC, zarathustra323 submitted a review, later dismissed

2021-07-21 17:11 UTC, zarathustra323 approved these changes

2021-07-21 17:11 UTC, merged