Support Base mutations for name, teaser, and body
parameter1/base-cms pull request #129
Opened 2021-07-21 21:07 UTC by solocommand

Requires #127 merged first to prevent conflicts in the updateContentMutationHandler

2021-07-21 21:10 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create GraphQL mutations to allow modification of company and event fields](https://trello.com/c/MNb1mVwT/101-create-graphql-mutations-to-allow-modification-of-company-and-event-fields)

2021-07-22 13:29 UTC, zarathustra323 requested changes
@solocommand lets get the other PRs resolved and merged and then re-base this to make sure all the changes are correct. it looks like the event mutation code bled into this PR

2021-07-22 13:29 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  "The mutation to target"
Update this to say `The mutation to target. The default/non-mutated value will be used when this is null or unset.`

2021-07-22 13:29 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  "The mutation to target"
Same here

2021-07-22 13:29 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  "The mutation to target"
Same here

2021-07-22 14:45 UTC, zarathustra323 approved these changes

2021-07-22 14:45 UTC, merged