Add support for customBooleanFields to the IdentityX profile component
parameter1/base-cms pull request #212
Opened 2022-01-05 17:49 UTC by B77Mills

Will require: https://github.com/parameter1/identity-x/pull/6
<img width="829" alt="Screen Shot 2022-01-05 at 11 35 10 AM" src="https://user-images.githubusercontent.com/3845869/148263987-5f2f1b09-c24e-4363-9056-a7a986cb3110.png">

2022-01-05 19:10 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to add checkbox fields to Identity-X](https://trello.com/c/adTAKA4F/258-how-to-add-checkbox-fields-to-identity-x)

2022-01-13 14:47 UTC, zarathustra323 requested changes

2022-01-13 14:47 UTC, zarathustra323 commented on packages/marko-web-identity-x/browser/profile.vue
> +      this.user.customBooleanFieldAnswers = this.customBooleanFieldAnswers;
I'm a bit confused by what's happening here... how is the change being applied if the array is just being reset to itself?

2022-01-13 20:04 UTC, B77Mills commented on packages/marko-web-identity-x/browser/profile.vue
> +      this.user.customBooleanFieldAnswers = this.customBooleanFieldAnswers;
@zarathustra323  I was missing a chunk of this from my site code.  Sorry it should take a answerId now and set the value to the opposite of what it was and also the user.customBooleanFieldAnsers to this.customBooleanAnswers

2022-01-17 15:20 UTC, zarathustra323 approved these changes

2022-01-17 15:20 UTC, merged