Use ```PUBLISHED DESC``` as default return order,
parameter1/base-cms pull request #214
Opened 2022-01-10 21:27 UTC by Shinsina

<img width="1920" alt="Screen Shot 2022-01-10 at 3 12 06 PM" src="https://user-images.githubusercontent.com/46794001/148841560-bf41d565-4628-4f80-9233-739bdea59d2b.png">
<img width="1920" alt="Screen Shot 2022-01-10 at 3 14 24 PM" src="https://user-images.githubusercontent.com/46794001/148841570-ce5175fa-4679-4227-b6a3-01e5dc86582c.png">
 
 This adds a Sort By list of filters which will list the filters only when a search query has been provided (typed in) (as currently only a relevance option is being provided, this logic could be modify should additional sorts be desired). 
 
 This additionally adds a variable to the GraphQL parameters called withSearchQueryDefault which defaults to ```PUBLISHED DESC``` sorting and can be set to relevance which will use ```SCORE DESC``` as was the behavior when searchQuery was provided previously. (withSearchQueryDefault itself defaults to date and can currently also be set to relevance to achieve the outlined affect)

2022-01-10 21:30 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add sort "by date" option to search results](https://trello.com/c/ivtGKIi1/131-add-sort-by-date-option-to-search-results)

2022-01-10 21:42 UTC, solocommand submitted a review, later dismissed
@Shinsina I think I see what you're doing here, but a couple UX changes:

`Sort by` should always be present, not only show up when using a search term. It shouldn't be referenced as a filter in the code (and IMO should be above the filters, not below).

All available sorting options should be visible in the sort by section, and unselectable items should be disabled (such as when a search term is not present).

The query loader shouldn't care about the search term being present, revert the default value and sort default changes -- this should be handled by the higher level component. Ideally this is just a function of the sort by list.

Just pass `SCORE` as the sortField when selecting relevance and this should work as-is.

2022-01-17 20:00 UTC, Shinsina commented
New comment to post various screenshots for the most recent set of updates to this PR:

Desktop, with searchQuery and sort applied:
<img width="1920" alt="Screen Shot 2022-01-17 at 1 34 49 PM" src="https://user-images.githubusercontent.com/46794001/149830428-976ac67e-8ef6-4cfa-b758-ac513bcebcdb.png">

Desktop, search landing page: 
<img width="1920" alt="Screen Shot 2022-01-17 at 1 35 22 PM" src="https://user-images.githubusercontent.com/46794001/149830483-95c93552-af39-44de-8446-aea16b7e3521.png">

Desktop, with existing filters applied only:
<img width="1920" alt="Screen Shot 2022-01-17 at 1 35 33 PM" src="https://user-images.githubusercontent.com/46794001/149830536-c5bc0865-dca9-4d26-95ad-a37081506c13.png">

Desktop, with existing filters AND searchQuery: 
<img width="1920" alt="Screen Shot 2022-01-17 at 1 35 44 PM" src="https://user-images.githubusercontent.com/46794001/149830615-51073d0a-0d53-454e-9e64-bcbf3d487647.png">

Desktop, with existing filters, searchQuery AND sort applied: 
<img width="1920" alt="Screen Shot 2022-01-17 at 1 35 57 PM" src="https://user-images.githubusercontent.com/46794001/149830654-9ef710ff-f63a-4eff-b843-1a224dde9012.png">

Mobile screenshots of previous:

<img width="515" alt="Screen Shot 2022-01-17 at 1 42 10 PM" src="https://user-images.githubusercontent.com/46794001/149830716-49362d9e-875f-45c1-9539-55042fd4d377.png">
<img width="807" alt="Screen Shot 2022-01-17 at 1 43 45 PM" src="https://user-images.githubusercontent.com/46794001/149830718-c2746bc1-e16c-4c47-a895-3323d4712b6a.png">
<img width="1216" alt="Screen Shot 2022-01-17 at 1 50 17 PM" src="https://user-images.githubusercontent.com/46794001/149830733-a5a80c49-8d2f-4dbb-8367-119ce899ecfb.png">

2022-01-18 15:41 UTC, zarathustra323 requested changes

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/browser/sort-select.vue
> +    nodes: {
Rename `nodes` to `options`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/browser/sort-select.vue
> +  props: {
Add `selectedId` prop and pass from marko component typed as a `String` with a default of `published_desc`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/browser/sort-select.vue
> +      :selected="item.isSelected"
`:selected="item.id === selectedId"`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/browser/sort-select.vue
> +    onChange(e) {
Change from `e` to `event`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/components/filters/selected/index.marko
> -$ const { contentTypes, assignedToWebsiteSectionIds } = search.input;
Discard all changes here

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/components/sort-by/index.marko
> +$ const items = search.config.sortBy;
Rename `items` to `options` and hard set here.
```js
const options = [
  { id: 'PUBLISHED', label 'Published' },
  { id: 'SCORE', label 'Relevancy' },
]
```

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/components/sort-by/index.marko
> +<if(items.length)>
This won't be needed now

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/config/index.js
> +   * @param {object[]} [params.sortBy] A list of filters for search results,
Discard changes

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/config/query-params.js
> +      .add('sortBy', {
Change `sortBy` to `sortField`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/config/query-params.js
>        });
At top of file, add: `const sortFieldSet = new Set('PUBLISHED', 'SCORE')`;

Add default: 
`defaultValue: 'PUBLISHED'`

Add validator:

```js
validator: v => sortFieldSet.has(v),
```

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/config/query-params.js
> +        toInput: toStringArrayInput,
Remove `toInput` and `fromInput`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/config/query-params.js
> +      })
Add: 
```js
.add('sortOrder', {
  type: String,
  defaultValue: 'DESC',
  validator: v => (v === 'DESC' || v === 'ASC'),
})
```

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/components/sort-by/index.marko
> +      <marko-web-browser-component name="MarkoWebSearchSortSelect" props={ nodes, searchQuery } />
Pass `sort-field=search.input.sortField` from website code, then `props={ options, selectedId: input.sortField }`

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/components/sort-by/index.marko
> +    $ const nodes = search.input.sortBy.length ? items.map((item) => {
The node mapping can go away

2022-01-18 15:41 UTC, zarathustra323 commented on packages/marko-web-search/components/sort-by/index.marko
> +        const urlSearchParams = new URLSearchParams(window.location.search);
This can go away

2022-01-18 18:09 UTC, zarathustra323 requested changes

2022-01-18 18:09 UTC, zarathustra323 commented on packages/marko-web-search/browser/sort-select.vue
> +      const urlSearchParams = new URLSearchParams(window.location.search);
```js
const url = new URL(window.location);
const params = new URLSearchParams(window.location.search);
params.set('sortField', value);
url.search = `${params}`;
window.location.href = `${url}`
```

2022-01-18 19:11 UTC, zarathustra323 requested changes

2022-01-18 19:11 UTC, zarathustra323 commented on packages/marko-web-search/browser/sort-select.vue
> +  <select :class="className" @change="onChange">
Change to `<select class="custom-select" @change="onChange">` and then remove the `className` from the props list.

2022-01-18 19:11 UTC, zarathustra323 commented on packages/marko-web-search/components/query.marko
> -  opSuffix: input.opSuffix,
Restore the trailing comma

2022-01-18 19:36 UTC, zarathustra323 approved these changes

2022-01-18 19:36 UTC, merged