Add export deployment tool
parameter1/base-cms pull request #217
Opened 2022-01-13 17:03 UTC by solocommand

CLI for parameter1/ab-media-exports#2

2022-01-24 15:17 UTC, zarathustra323 requested changes, later dismissed

2022-01-24 15:17 UTC, zarathustra323 commented on packages/export-deployment-tool/package.json
> +  "version": "0.0.0",
This should be set to the current version in `lerna.json`

2022-01-24 15:17 UTC, zarathustra323 commented on packages/export-deployment-tool/package.json
> +    "eslint": "^5.16.0",
The dev dependencies can be removed. These are already install at the root level

2022-03-07 16:29 UTC, brandonbk approved these changes

2022-03-07 16:31 UTC, merged