Add UserRegistration to graph definition & resolver
parameter1/base-cms pull request #226
Opened 2022-01-26 21:08 UTC by B77Mills

Add the new UserRegistration fields to the graph definition & resolvers also add the mutation support for UserRegistration

2022-01-26 21:10 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Content UserRegistration by date management components](https://trello.com/c/IrcXjRpf/10-content-userregistration-by-date-management-components)

2022-01-26 23:55 UTC, zarathustra323 requested changes

2022-01-26 23:55 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  accessLevels: [String]
Ensure all array items are non-nullable and all defaults are set to empty, so:

`accessLevels: [String!] = []`
`siteIds: [ObjectID!]! = []`

2022-01-26 23:55 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  isRequired: Boolean
`isRequired` should be non-nullable

2022-01-26 23:55 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  "Is Registration Required"
Clean up the comments to be more declarative.. e.g. "Whether registration is required to view the content"

And for dates.... "The date when the registration requirement begins" etc

2022-01-26 23:55 UTC, zarathustra323 commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  accessLevels: [String]
Actually, it doesn't look like the resolver is handling access levels or site IDs, so just remove these from the input definition for now

2022-01-27 16:50 UTC, zarathustra323 approved these changes

2022-01-27 16:50 UTC, merged