Addition of ```sectionStartDate``` field and field resolver.
parameter1/base-cms pull request #247
Opened 2022-02-15 17:14 UTC by Shinsina

<img width="1295" alt="Screen Shot 2022-02-15 at 10 57 11 AM" src="https://user-images.githubusercontent.com/46794001/154111745-7b147457-9e9f-47c2-856d-e02af336118c.png">

Accessing this appropriately on site is difficult as https://github.com/parameter1/base-cms/blob/master/packages/web-common/src/utils/extract-fragment-name.js currently blocks fragments as functions (this is easily fixed by calling the fragment function and doing the same Document kind check that is being done there already), Additionally things like ```marko-web-load-more``` also do not account for fragments as functions and suffers from the same previously described issue of the fragment name extractor and other helper functions not accounting for fragments as functions.

The workaround I am currently working with can be found here: https://github.com/parameter1/allured-business-media-websites/pull/249, however it currently only works in Allured's utility block loader (the file modification can be viewed here: https://github.com/parameter1/allured-business-media-websites/blob/ca1333707d9b0dab5dda0932738d5a80e09d9e79/packages/shared/loaders/website-section-content.js), this does not extend to load more or any other places in which queries for content are being done as was previously explained in this PR.

Looking for thoughts as to how to handle this and places in which the respective fragments are used and handling passing in input etc.

2022-02-15 17:17 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update GraphQL API to return current section scheduled date](https://trello.com/c/HgTodiyh/280-update-graphql-api-to-return-current-section-scheduled-date)

2022-02-15 18:22 UTC, solocommand requested changes

2022-02-15 18:22 UTC, solocommand commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +      const descendantIds = await getDescendantIds(sectionId, basedb);
This should only happen if section bubbling is enabled. Add that to the input and only get the descendant ids in that case. Check the `websiteScheduledContent` query, match the input key and default value here as well (I believe on by default, but double check please!)

The rest of your logic should stay the same...something like `ids = useSectionBubbling ? await getDescendantIds() : [sectionId];`

2022-02-15 18:22 UTC, solocommand commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +      return sectionDates[0];
We don't care about uniqueness, you should just be able to do something like this
```js
  return schedules.length ? schedules[0].start : null;
```

2022-02-15 18:22 UTC, solocommand commented on services/graphql-server/src/graphql/definitions/platform/content/interfaces/content.js
> +
Add a GraphQL doc line above this field to indicate the expected use.

2022-02-15 18:22 UTC, solocommand commented on services/graphql-server/src/graphql/definitions/platform/content/index.js
> +  sectionId: Int
Add GraphQL docs here to indicate what the input is used for and what each field (including the new flag) does

2022-02-15 18:25 UTC, solocommand commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +        .map(section => section.start);
I wasn't explicit about it in my review, but combine these. There's no need to create two arrays just to join them again later. The website section ID is always included in its own descendant ids, but you can also just include it in your ids to check.
```js
const ids = [
  sectionId,
  ...(useSectionBubbling ? await getDescendantIds(...) : []),
];

2022-02-16 17:44 UTC, zarathustra323 commented
@Shinsina we're going to hold on these changes for now, pending some other options

2024-04-08 19:50 UTC, closed without merging