Add city, street, extra fields, hidden support
parameter1/base-cms pull request #248
Opened 2022-02-15 21:41 UTC by solocommand

Adds support for `city`, `street`, and `addressExtra` within IdentityX. Reorders form fields (slightly) to make for a more consistant layout when these fields are not displayed (the default)

| Description | Screenshot |
| - | - |
| Current (NA) | <img width="693" alt="image" src="https://user-images.githubusercontent.com/1778222/154152997-9df9631b-4a38-4481-b7a7-35e135dc3205.png">
| Current (non-NA) | <img width="687" alt="image" src="https://user-images.githubusercontent.com/1778222/154153083-4ac8f312-b18e-45ca-9e42-61224a5a5c60.png">
| New with fields shown (NA) | <img width="684" alt="image" src="https://user-images.githubusercontent.com/1778222/154152138-065ae36d-90ca-4f75-8278-24974ec06e38.png">
| New with fields shown (non-NA) | <img width="687" alt="image" src="https://user-images.githubusercontent.com/1778222/154153757-b5801a07-1097-4153-8399-55696688c6c8.png">
| New with fields hidden (NA) | <img width="684" alt="image" src="https://user-images.githubusercontent.com/1778222/154152764-559741fa-655f-4db9-969d-80a6f86e1008.png">
| New with fields hidden (non-NA) | <img width="682" alt="image" src="https://user-images.githubusercontent.com/1778222/154152844-7d5c3f97-cfb5-4d9a-b5ba-467278f78e1a.png">

2022-02-16 19:13 UTC, solocommand commented
@zarathustra323 field layout/logic updated as we discussed and new screenshots added.

2022-02-17 13:58 UTC, zarathustra323 requested changes

2022-02-17 13:58 UTC, zarathustra323 commented on packages/marko-web-identity-x/browser/profile.vue
> +        required: this.isFieldRequired('organizationTitle'),
Unfortunately can't use the function calls here either otherwise changes to the array won't trigger a change to the computed prop.

2022-02-17 17:25 UTC, zarathustra323 approved these changes

2022-02-17 17:25 UTC, merged