Add website config mutations
parameter1/base-cms pull request #259
Opened 2022-03-16 15:54 UTC by Shinsina

2022-03-16 16:08 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create graph mutation to allow creation and modification of WebsiteSite.](https://trello.com/c/Wvg0SmuZ/25-create-graph-mutation-to-allow-creation-and-modification-of-websitesite)

2022-03-17 16:01 UTC, solocommand requested changes
Rename fields and inputs to include the modelspace prefix, e.g; `updateWebsiteSiteHost`

2022-03-17 16:09 UTC, solocommand requested changes

2022-03-17 16:09 UTC, solocommand commented on services/graphql-server/src/graphql/definitions/website/site.js
> +  updateWebsiteSiteAssetHost(input: UpdateSiteAssetHostInput!): WebsiteSite! @requiresAuth
Inputs don't match now

2022-03-17 17:42 UTC, solocommand requested changes

2022-03-17 17:42 UTC, solocommand commented on services/graphql-server/src/graphql/definitions/website/site.js
> +
`host` `imageHost` and `assetHost` are not nullable in the GraphQL [definition](https://github.com/parameter1/base-cms/blob/master/services/graphql-server/src/graphql/definitions/website/site.js#L12) for the `WebsiteSite` type, so the input shouldn't allow a null value to be passed/set. Change these to `: String!` instead of `: String` to enforce this. The `url` field _is_ nullable, so it can stay as-is.

2022-03-17 18:12 UTC, solocommand approved these changes

2022-03-17 18:12 UTC, merged