Add fragment, query & query loader for related advertiser stories
parameter1/base-cms pull request #266
Opened 2022-03-31 19:57 UTC by B77Mills

**Requires: https://github.com/parameter1/fortnight-graph/pull/11**

On the website side we can then use the query loader to return an array of nativeX story nodes converted to content nodes using something like:

```marko
import convert from "@parameter1/base-cms-marko-web-native-x/utils/convert-story-to-content";

<marko-web-resolve|{ resolved }| promise=advertiserRelatedStories({
  config: nativeX,
  advertiserId: story.advertiser.id,
  publisherId: nativeX.publisherId,
  excludeStoryIds: [story.id],
})>
  $ const { nodes } = resolved;
  <marko-web-node-list
    inner-justified=true
    flush-x=true
    flush-y=false
    modifiers=["section-feed"]
  >
    <@header>
      More from ${story.advertiser.name}
    </@header>
    <@nodes nodes=nodes>
      <@slot|{ node }|>
        <theme-section-feed-content-node
          node=convert(node)
          display-image=true
          with-section=false
          lazyload=false
        />
      </@slot>
    </@nodes>
  </marko-web-node-list>
</marko-web-resolve>
```

Resulting in:
<img width="1102" alt="Screen Shot 2022-03-31 at 2 51 54 PM" src="https://user-images.githubusercontent.com/3845869/161137717-7a7a1281-ff83-468e-9940-4bb871ba540c.png">

2022-03-31 20:02 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable a "View All" page for Partner Insights advertisers](https://trello.com/c/RQdP3bi6/115-enable-a-view-all-page-for-partner-insights-advertisers)

2022-04-14 14:20 UTC, solocommand requested changes

2022-04-14 14:20 UTC, solocommand commented on packages/marko-web-native-x/components/story/advertiser-related-stories.marko
> +  $ warn('Unable to fetch elements from NativeX: a uri and placement ID are required.');
Advertiser ID

2022-04-14 14:20 UTC, solocommand commented on packages/marko-web-native-x/components/story/advertiser-related-stories.marko
> +import createClient from "../../apollo/create-client";
This import is no longer needed if you're moving the Nx client creation to the config.

2022-04-21 14:36 UTC, solocommand approved these changes

2022-04-21 14:36 UTC, merged