Add length check to content teaser
parameter1/base-cms pull request #276
Opened 2022-04-11 16:49 UTC by B77Mills

Add the check for the length of the value being longer that maxLength when the html is stripped and spaces are removed. If not return the original value.

2022-04-11 17:20 UTC, jwade1327 submitted a review, later dismissed

2022-04-11 17:53 UTC, solocommand requested changes

2022-04-11 17:53 UTC, solocommand commented on services/graphql-server/src/graphql/utils/content-teaser.js
No need to run the strip twice

```suggestion
  if (!maxLength) return value;
  // @todo This strips HTML from truncated teasers. We could attempt to preserve it?
  const stripped = stripHtml(value);
  if (stripped.replace(' ', '').length <= maxLength) return value;
```

2022-04-12 14:34 UTC, solocommand approved these changes

2022-04-12 14:35 UTC, merged