Create new dynamic loader for the reCAPTCHA script inclusion
parameter1/base-cms pull request #309
Opened 2022-05-20 18:48 UTC by B77Mills

Add new dynamic loading of reCAPTCHA v3 script on submit of the newsletter signup forms.

2022-05-24 19:16 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Consolidate reCAPTCHA script in Monorail, contact us & inquiry forms.](https://trello.com/c/v7Jvf8te/97-consolidate-recaptcha-script-in-monorail-contact-us-inquiry-forms)

2022-05-25 16:07 UTC, zarathustra323 requested changes

2022-05-25 16:07 UTC, zarathustra323 commented on docker-compose.yml
> +      RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-}
Prefix the right-side values with `EXAMPLE_` (like the above)... e.g. `RECAPTCHA_V3_SECRET_KEY: ${EXAMPLE_RECAPTCHA_V3_SECRET_KEY-}`

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/README.md
> +# BaseCMS Object Path
Update this file to reflect recaptcha, not object path :)

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/browser/.eslintrc.js
> +    'vue/max-attributes-per-line': ['error', {
Remove this

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/browser/.eslintrc.js
> +    'plugin:vue/recommended',
Remove this

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/browser/get-token.js
> +export default ({
```js
export default ({ siteKey, action }) => {
  if (!siteKey) throw new Error('The recaptcha site key is required');
  if (!action) throw new Error('The recaptcha action is required');
  return window.grecaptcha.execute(siteKey, { action });
}
```

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/src/validate-token.js
> +  const submitActions = actions || [];
`if (!actions || !actions.length) throw new Error('At least one recaptcha action is required')`

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/src/validate-token.js
> +  const submitActions = actions || [];
Then remove `submitActions` and use `actions` directly

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/src/validate-token.js
> +  const score = minimumScore || 0.5;
Also throw error if token or secretKey are missing

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/src/validate-token.js
> +  if (!recaptchaData.success || !submitActions.includes(recaptchaData.action) || recaptchaData.score < score) throw createError(400, 'Unable to validate request because reCAPTCHA failed.');
Throw individual error for each error condition

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/browser/load.js
> +  if (!recaptchaLoadPromise) recaptchaLoadPromise = recaptchaLoad(siteKey);
`if (!window.recaptchaLoadPromise) window.recaptchaLoadPromise = recaptchaLoad(siteKey);`

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/browser/load.js
> +let recaptchaLoadPromise;
Delete this since the `window` global will be used

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-contact-us/browser/form.vue
> +        <p
Move this to the top of the row and change to `v-if` instead of `v-else-if`

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-inquiry/browser/default-form.vue
> +      An error occurred: {{ recaptcha.error.message }}
Change to `A recaptcha error occurred`

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-contact-us/browser/form.vue
> +        <p
And use `A recaptcha error occurred` instead of the errorLabel

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-inquiry/routers/submit.js
> -  if (!payload || payload.email === '') {
Add this back but change to:

```js
if (!payload || !payload.email) {
  throw exception('Invalid form submission');
}
```

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-inquiry/routers/submit.js
> -  const exception = (message, code = 400) => {
Restore this

2022-05-25 16:07 UTC, zarathustra323 commented on packages/marko-web-recaptcha/src/validate-token.js
> +  if (!recaptchaData.success || !actions.includes(recaptchaData.action) || recaptchaData.score < minimumScore) throw createError(400, 'Unable to validate request because reCAPTCHA failed.');
Throw for each error type

2022-05-25 16:07 UTC, zarathustra323 commented on services/example-website/browser/index.js
> +// import OmedaIdentityX from '@parameter1/base-cms-marko-web-omeda-identity-x/browser';
Delete the commented out code

2022-05-25 18:40 UTC, zarathustra323 approved these changes

2022-05-25 18:50 UTC, merged