Support for Image Alt input
parameter1/base-cms pull request #310
Opened 2022-05-24 15:35 UTC by Shinsina

<img width="1792" alt="Screen Shot 2022-05-24 at 10 29 58 AM" src="https://user-images.githubusercontent.com/46794001/170075171-0c67da8a-370d-4c23-9398-6393597cfb1d.png">
<img width="1792" alt="Screen Shot 2022-05-24 at 10 30 12 AM" src="https://user-images.githubusercontent.com/46794001/170075189-cbb05a95-ff78-4380-96ad-af0bac759008.png">
<img width="1920" alt="Screen Shot 2022-05-24 at 10 30 21 AM" src="https://user-images.githubusercontent.com/46794001/170075194-2a345a83-c8c6-4515-a2c6-da4c28d3de24.png">
<img width="1792" alt="Screen Shot 2022-05-24 at 10 30 39 AM" src="https://user-images.githubusercontent.com/46794001/170075202-49fd7fc4-69f4-4531-a337-f7d04f472fb9.png">
<img width="1917" alt="Screen Shot 2022-05-24 at 10 30 42 AM" src="https://user-images.githubusercontent.com/46794001/170075206-560aa1bc-df13-43dc-913b-bd8761e14322.png">

This will also allow us to prepend something like "Photo of:" to all alt attributes (to account for instances like the remaining violation here)

2022-05-24 15:36 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility improvements](https://trello.com/c/7OYysXzp/130-accessibility-improvements)

2022-05-25 18:47 UTC, zarathustra323 requested changes

2022-05-25 18:47 UTC, zarathustra323 commented on services/graphql-server/src/graphql/resolvers/platform/asset.js
> +    alt: (image, { input = {} }) => createAltFor(image, input),
`({ ...image, ...input })`

2022-05-25 18:47 UTC, zarathustra323 commented on packages/image/src/create-alt-for.js
> +} = {}, { prepend, append } = {}) => {
Move into main params

2022-05-25 18:47 UTC, zarathustra323 commented on packages/image/src/create-alt-for.js
> +  if (prepend) {
Remove the prepend/append ifs

2022-05-25 18:47 UTC, zarathustra323 commented on packages/image/src/create-alt-for.js
>    if (displayName) return clean(displayName);
`if (displayName) return clean(displayName, { prepend, append });`

2022-05-25 18:47 UTC, zarathustra323 commented on packages/image/src/create-alt-for.js
>    if (displayName) return clean(displayName);
```js
const strip = v => htmlEntities.encode(stripHtml(v));

const clean = (v, { prepend, append }) => {
  const values = [];
  if (prepend) values.push(strip(prepend));
  values.push(strip(v));
  if (append) values.push(strip(append));
  return values.join(' ');
};
```

2022-05-25 19:12 UTC, zarathustra323 approved these changes

2022-05-25 19:12 UTC, merged