IdentityX+Omeda customer data resync
parameter1/base-cms pull request #321
Opened 2022-06-02 20:43 UTC by solocommand

Currently, the `onActiveContext` hook is firing after the response is sent (due to streaming), meaning that the cookie changes that are being attempted are never actually being written. The first set of changes here moves this logic to a middleware to ensure that it can be attempted before the streamed response is sent. Since this hook now has no logic, it was removed entirely.

A new middleware was added to handle resyncing of customer data: setting custom boolean and select field answers based on the external ids present in the IdentityX user's related Omeda customer record. This works by setting an `__idx_omeda_resync` cookie with a 1 week expiration. This expiration can be customized via the IdentityX configuration file, using the key `userResyncInterval`:
```js
module.exports = new IdentityXConfiguration({
  // ...
  userResyncInterval: 24 * 60 * 60 * 1000, // Run daily
});

Finally, a significant portion of the logic used in `onLoginLinkSent` was extracted so it can be re-used by the resync middleware.

2022-06-02 20:43 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add configurable external provider sync hook/middleware handler](https://trello.com/c/9LrAEgh5/17-add-configurable-external-provider-sync-hook-middleware-handler)

2022-06-02 23:28 UTC, zarathustra323 reviewed
Can we table this until I'm back from Portland on Tuesday? Would like to go over it in person.

2022-06-13 20:52 UTC, zarathustra323 requested changes

2022-06-13 20:52 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/middleware/set-olytics-cookie.js
> +}) => async (req, res, next) => {
Wrap this in the `asyncRoute` helper

2022-06-13 20:52 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/middleware/resync-customer-data.js
> +}) => async (req, res, next) => {
Use the `asyncRoute` util

2022-06-13 20:52 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/add-integration-hooks.js
> -  idxConfig.addHook({
Check if token is set before querying the GraphQL API in `loadActiveContext`

2022-06-13 20:52 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/middleware/resync-customer-data.js
> +  const encryptedCustomerId = findEncryptedId({ externalIds: getAsArray(user, 'externalIds'), brandKey });
Add `if(!user || !user.id) return next();` Then remove the user from the if check on L27

2022-06-13 20:52 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/middleware/resync-customer-data.js
> +
Add `if (!encryptedCustomerId) return next();`

2022-06-13 20:52 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/middleware/resync-customer-data.js
> +    if (encryptedCustomerId && !cookie) {
Same here, bail early.

2022-06-17 16:54 UTC, zarathustra323 requested changes
Also, I see there are some `@todo` items listed... should these be addressed now?

2022-06-17 16:54 UTC, zarathustra323 commented on packages/marko-web-identity-x/service.js
> +    if (!this.activeContextQuery && this.token) {
For clarity, move to a line above: `if (!this.token) return {}`

2022-06-17 17:06 UTC, solocommand commented
@zarathustra323 Done, those are accounted for but left the comments by accident

2022-06-17 17:07 UTC, zarathustra323 approved these changes

2022-06-17 17:12 UTC, merged