Ensure that the email input has a unique Id
parameter1/base-cms pull request #328
Opened 2022-06-08 18:29 UTC by B77Mills

This add support of passing in a id to email.vue component in order to ensure that the login email input is unique.  By default when calling the email.vue component on its own it will still use sign-on-email as the id.

2022-06-08 18:36 UTC, Shinsina commented on packages/marko-web-identity-x/browser/form/fields/email.vue
> +      default: 'sign-on-email'
Missing trailing comma.

2022-06-08 18:42 UTC, Shinsina commented on packages/marko-web-identity-x/browser/login.vue
> +    this.loginInputId = `${this.loginInputId}-${this._uid}`;
The linter doesn't seem to like _uid (causing the Travis build to fail), either add the appropriate eslint-ignore/disable comment to the line prior to this or try using dynamic property access ```this['_uid']```

2022-06-08 22:02 UTC, Shinsina commented on packages/marko-web-identity-x/browser/utils/uid.js
> +    for (buffer = '', idx = 0; i < size; i++) {
Should be able to do i += 1 here and remove the eslint-disable no-plusplus

2022-06-09 13:57 UTC, zarathustra323 requested changes

2022-06-09 13:57 UTC, zarathustra323 commented on packages/marko-web-identity-x/browser/form/fields/email.vue
>      email: {
```js
id() {
  return elementId('identity-x-email-field');
},
```

2022-06-09 13:57 UTC, zarathustra323 commented on packages/marko-web-identity-x/browser/form/fields/email.vue
>  import FormGroup from '../common/form-group.vue';
```js
import elementId from '@parameter1/base-cms-marko-web/browser/components/element-id';
```

2022-06-09 14:55 UTC, zarathustra323 approved these changes

2022-06-09 14:56 UTC, merged