Add sponsored search support to search page and site-navbar
parameter1/base-cms pull request #361
Opened 2022-06-30 14:00 UTC by B77Mills

- Add support for setting a searchSponsor within the site config.
 ```js
 searchSponsor: {
  headerLogo: {
    alt: 'Search Sposored by ProfiNet',
    src: 'https://img.automationworld.com/files/base/pmmi/aw/profinet_black.png?h=24&auto=format,compress',
    srcset: [
      'https://img.automationworld.com/files/base/pmmi/aw/profinet_black.png?h=24&auto=format,compress&dpr=2 2x',
    ],
  },
  pageLogo: {
    alt: 'Search Sposored by ProfiNet',
    src: 'https://img.automationworld.com/files/base/pmmi/aw/profinet_green.png?h=48&auto=format,compress',
    srcset: [
      'https://img.automationworld.com/files/base/pmmi/aw/profinet_green.png?h=48&auto=format,compress&dpr=2 2x',
    ],
  },
},
```
- Add support to the site-navbar call to display search icon & conditionally display the sponsor logo when set.  
- Add ability to also tell the site-menu-toggle to display left or right
- Example site call looks like `<theme-site-header has-user=hasUser reg-enabled=isEnabled show-search-icon=true menu-btn-position="right"/>`
<img width="1205" alt="Screen Shot 2022-06-30 at 8 59 41 AM" src="https://user-images.githubusercontent.com/3845869/176696676-08baa458-96d8-4fa5-8dc9-38eb3b15687f.png">

2022-07-05 19:21 UTC, brandonbk requested changes

2022-07-05 19:21 UTC, brandonbk commented on packages/marko-web-theme-monorail/components/site-menu/components/search.marko
> +          class="search-sponsor__logo lazyload"
Remove lazyload from this since it is above the fold

2022-07-07 17:22 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Search to top nav, remove from hamburger nav and we need sponsored search for AW](https://trello.com/c/dWBy0hVn/353-add-search-to-top-nav-remove-from-hamburger-nav-and-we-need-sponsored-search-for-aw)

2022-07-07 17:51 UTC, brandonbk approved these changes

2022-07-07 17:58 UTC, merged