IdentityX Omeda product subscription support
parameter1/base-cms pull request #365
Opened 2022-07-07 16:40 UTC by solocommand

- [ ] Requires parameter1/omeda#28

Adds support for sending product subscriptions for IdentityX questions with the `product` entity type.

2022-07-07 16:41 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Support `product` entity type subscription fields](https://trello.com/c/8CAohakI/21-support-product-entity-type-subscription-fields)

2022-07-12 15:33 UTC, zarathustra323 requested changes

2022-07-12 15:33 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/integration-hooks/on-login-link-sent.js
> +    });
Products and the `brandKey` option need to be handled in https://github.com/parameter1/base-cms/blob/master/packages/marko-web-omeda-identity-x/middleware/resync-customer-data.js

2022-07-12 15:33 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/integration-hooks/on-login-link-sent.js
> +    await setOmedaProducts({
Only sync each type if data is missing for that type. Do _not_ promise all these

2022-07-12 15:33 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/integration-hooks/on-login-link-sent.js
> +      brandKey,
Move the sync operations to their own file and re-use in resync-customer-data... then add options for which types should actually fire....

```js
module.exports = async ({
  identityX,
  brandKey,
  user,
  omedaCustomer,
  omedaLinkedFields,
}, {
  shouldUpdateDemographics =  false,
  shouldUpdateDeploymentTypes =  false,
  shouldUpdateProducts =  false,
} = {}) => {
  if (shouldUpdateDemographics) {
    await setOmedaDemographics({
      identityX,
      brandKey,
      user,
      omedaCustomer,
      fields: omedaLinkedFields.demographic,
    });
  }
  // ...
}
```

2022-07-14 18:44 UTC, zarathustra323 requested changes

2022-07-14 18:44 UTC, zarathustra323 commented on packages/marko-web-omeda-identity-x/omeda-data/update-identity-x.js
> +  console.log('Updating IdentityX Data', {
Remove console.log

2022-07-14 18:46 UTC, zarathustra323 approved these changes

2022-07-14 18:55 UTC, merged