Omeda+IdentityX Behavior support
parameter1/base-cms pull request #385
Opened 2022-07-27 20:05 UTC by solocommand

- IdentityX: Export list of valid hook names
- Omeda: Pass `behaviors` field through to the GraphQL API
- Omeda+IdentityX
  - Support setting custom behaviors, demographics, and promo codes for IdentityX events
  - Add rapid identification call to `onAuthenticationSuccess`

2022-07-27 20:06 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Utilize Behaviors for tracking verification status in Omeda](https://trello.com/c/qUfrU3v2/22-utilize-behaviors-for-tracking-verification-status-in-omeda)

2022-08-09 15:46 UTC, zarathustra323 requested changes

2022-08-09 15:46 UTC, zarathustra323 commented on packages/marko-web-identity-x/browser/profile.vue
> +          ...this.user,
```js
{
  ...this.user,
  additionalEventData: {
    actionSource: this.source, // Set default value if not passed in
    ...this.additionalEventData,
  },
}
```

2022-08-09 15:52 UTC, zarathustra323 requested changes

2022-08-09 15:52 UTC, zarathustra323 commented on packages/marko-web-identity-x/browser/login.vue
> +            actionSource: 'default', // Set source default
`actionSource: this.source`

2022-08-11 14:39 UTC, zarathustra323 approved these changes

2022-08-11 14:39 UTC, merged