Ad injection logic modification for when images are contained within a paragraph.
parameter1/base-cms pull request #425
Opened 2022-09-12 16:57 UTC by Shinsina

PROD:
![Ad-Injection-PROD](https://user-images.githubusercontent.com/46794001/189712333-6a980893-2ef0-4f11-b42c-bff5d17013cf.png)

DEV:
![Ad-Injection-DEV](https://user-images.githubusercontent.com/46794001/189712363-c8a6168c-badc-49c4-a264-5dff3e9e4741.png)

This somewhat resolves the issue of "floating images" coming from when ad's are injected into the body copy. It's imperfect due to the nature of how this is already being handled as there is not an easy way to indicate when a paragraph or subsequent element in long enough to pull up to slot alongside the image.

2022-09-12 17:00 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Text wrapping around images](https://trello.com/c/bJSJ372R/472-text-wrapping-around-images)

2022-09-12 17:01 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue w/ad spacing and photos](https://trello.com/c/VDQmiUZ5/297-issue-w-ad-spacing-and-photos)

2022-09-12 19:03 UTC, zarathustra323 requested changes

2022-09-12 19:03 UTC, zarathustra323 commented on packages/marko-web-gam/browser/inject-ads.vue
> +                $child.children().each(function injectAdsChild() {
Change function name from `injectAdsChild` to `checkForChildEmbeds`

2022-09-12 19:03 UTC, zarathustra323 commented on packages/marko-web-gam/browser/inject-ads.vue
> +                if (hasInParagraphImage) $next.after(cleaned);
Change conditional statement to use multiple lines
```js
if () {
  //
} else {
  //
}
```

2022-09-16 16:52 UTC, zarathustra323 approved these changes

2022-09-16 16:53 UTC, merged