Add emptyHTML function to only return transcripts that are not empty
parameter1/base-cms pull request #491
Opened 2022-11-16 14:52 UTC by B77Mills

This will insure that the transcript field is actually set to something with text in it vs empty html.  Before if you cleared out or the user has just save a couple of empty html element it would return and display what looked to be nothing, but was really emply p  & h tags.  This check looks to see if there is actually text to render within the given html elements.

For example if you clear out the transcript field or hit return once in the field and save the model you now have an empty <p></p> saved in the value for transcript.  This new check would see that value as empty when it convert the html to text and trim the whitespace.  It will return a null value instead of an empty html string.

This should allow for this [PR](https://github.com/parameter1/industrial-media-websites/pull/287) to be closed, but the site repos will have to have a dep upgrade done to prevent empty transcript fields from displaying.

2022-11-16 14:54 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add new transcript field to remaining sites.](https://trello.com/c/plo9g5C6/150-add-new-transcript-field-to-remaining-sites)

2022-11-16 16:46 UTC, zarathustra323 requested changes

2022-11-16 16:46 UTC, zarathustra323 commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +  ContentPodcast: {
```js
/**
 *
 */
ContentPodcast: {
  transcript: ({ transcript }) => convertEmptyHtmlToNull(transcript),
},
```

2022-11-16 16:46 UTC, zarathustra323 commented on services/graphql-server/src/graphql/resolvers/platform/content.js
> +const convertEmptyHtmlToNull = async (html) => {
Remove `async`

2022-11-17 00:55 UTC, zarathustra323 approved these changes

2022-11-17 00:55 UTC, merged