Add SSR html body ad injection components.
parameter1/base-cms pull request #494
Opened 2022-11-22 15:29 UTC by B77Mills

This ads a the components needed to be able to pass in a adInjectionConfig to be able to configure which ad showes up at which conut with a list of modifiers.

The default ad configs is:
```js
$ const adInjectionConfig = defaultValue(input.adInjectionConfig, [
  {
    name: 'inline-content-desktop',
    modifiers: ["margin-auto-x",  "inline-content", "inline-content-desktop"],
    counts: [1000, 2750, 4500, 6250, 8000, 9750, 11500, 13250, 15000, 16750, 18500],
  },
  {
    name: 'inline-content-mobile',
    modifiers: ["margin-auto-x",  "inline-content", "inline-content-mobile"],
    counts: [250, 900, 1650, 2950, 4250, 5550, 6850, 8150, 9450, 10750, 12050, 13350, 14650, 15950, 17250],
  }
]);
```

2022-11-22 17:01 UTC, zarathustra323 requested changes

2022-11-22 17:01 UTC, zarathustra323 commented on packages/marko-web-theme-monorail/components/ssr-html-inject.marko
> +            if ($(toInsert).data() && $(toInsert).data().bamZoneAlias && $(toInsert).data().bamZoneAlias === $next.data().bamZoneAlias) return;
this is only account for Broadstreet, not GAM... will need to determine how to handle both.

2022-11-23 14:39 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [CLS: Body copy shifting when ads load on mobile](https://trello.com/c/aQnuynEI/193-cls-body-copy-shifting-when-ads-load-on-mobile)

2022-11-30 13:25 UTC, brandonbk requested changes

2022-11-30 13:25 UTC, brandonbk commented on packages/marko-web-theme-monorail/components/content/body-with-injection.marko
> +$ const desktopAdDataPropToPrevetDups = defaultValue(input.desktopAdDataPropToPrevetDups, "gamTemplateName");
@B77Mills - replace `PrevetDups` with `PreventDupes` in all files.  Missing the letter "n" in Prevent, and "e" in Dupes.

2022-11-30 19:31 UTC, brandonbk approved these changes

2022-11-30 19:31 UTC, merged