Add GTM container id to Nx middleware
parameter1/base-cms pull request #61
Opened 2021-03-31 18:24 UTC by solocommand

2021-03-31 18:25 UTC, zarathustra323 approved these changes

2021-03-31 18:28 UTC, zarathustra323 requested changes

2021-03-31 18:28 UTC, zarathustra323 commented on packages/marko-web-native-x/middleware/with-story.js
> +const gtmContainerId = process.env.NATIVE_X_GTM_CONTAINER_ID || 'GTM-PVHD8N5';
Actually I changed my mind. Pass this in as a middleware option with the default value set.

2021-03-31 18:42 UTC, closed without merging

2021-04-02 16:10 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Embed Native-X stories within the site](https://trello.com/c/rHbOMWJt/48-embed-native-x-stories-within-the-site)