Enforce 16/9 aspect ratio, oembedType === 'link'
parameter1/base-cms pull request #621
Opened 2023-03-03 04:01 UTC by Shinsina

This likely warrants discussion as I believe this may impact FCP (First Contentful Paint) and CLS (Content Layout Shift).

Live:
![Screenshot from 2023-03-02 21-54-00](https://user-images.githubusercontent.com/46794001/222628305-dd1fa603-69d6-45b2-a5e1-a81249c8628e.png)

Dev:
![Screenshot from 2023-03-02 21-54-03](https://user-images.githubusercontent.com/46794001/222628308-76daf930-8e02-4179-90d1-0ca7fdcf5f5c.png)
![Screenshot from 2023-03-02 21-54-18](https://user-images.githubusercontent.com/46794001/222628310-baca0c88-8f9e-4840-a7fc-1a05e491bfd9.png)

2023-03-03 18:03 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Video embed getting cut off](https://trello.com/c/EWeQG3Fc/109-video-embed-getting-cut-off)

2023-03-04 04:23 UTC, zarathustra323 requested changes
The issue is that, somehow, the video was added with a wrapping `data-oembed-type="link"` instead of `data-oembed-type="video"`

If changed to the latter the aspect ratio is applied.

Current (note the oembed type of `link`):
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/3289485/222875437-35c70e5d-c1ce-4df7-b030-20072b3aa68b.png">

After changing the `data-oembed-type` to `video`:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/3289485/222875466-080a442e-9e28-4994-ab7f-26a1fff21751.png">

2023-03-06 18:33 UTC, zarathustra323 requested changes

2023-03-06 18:33 UTC, zarathustra323 commented on services/oembed/src/app.js
> +  if (url.match(/player|video/) && videoProvider.has(data.provider_name)) return { ...data, type: 'video' };
Should this be an `&&` or an `||`?

2023-03-06 21:08 UTC, zarathustra323 approved these changes

2023-03-06 21:17 UTC, merged