Line up structured data for Companies with Schema.org definition for `Organization`
parameter1/base-cms pull request #659
Opened 2023-03-21 15:44 UTC by Shinsina

Removes the following:

`datePublished
dateModified
thumbnailUrl
headline`

MOVES the following `isBasedOn` from `root` to `url.isBasedOn`

Previously these were inheriting the same fields as `"@type": 'Article'` through spreading `defaultStruturedData` (now corrected to `defaultStructuredData`) prior to the additions of any company/organization specific fields, however due to https://schema.org/Article inheriting from https://schema.org/CreativeWork and https://schema.org/Organization **not** this causes some of those included schema definitions like `datePublished` or `headline` to be invalid as they aren't a part of the definition for https://schema.org/Organization additionally this alters the location for `isBasedOn` from the root of the schema to `url.isBasedOn` when working with the Organization schema type/definition.

PROD:
![Screenshot from 2023-03-23 11-17-05](https://user-images.githubusercontent.com/46794001/227267473-bed550a0-86ae-4d75-9202-5c292f3af495.png)

DEV:
![Screenshot from 2023-03-23 11-17-11](https://user-images.githubusercontent.com/46794001/227267507-77837e43-00ed-48bb-a56a-d6eda8ce3187.png)

Ref:
https://schema.org/Organization
https://schema.org/Article
https://github.com/parameter1/pmmi-prosource/pull/29
https://github.com/parameter1/pmmi-prosource/pull/30
https://trello.com/c/BNFf0dgc/491-seo-prosource-18-structure-data-items-are-invalid

2023-03-21 15:45 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Structured Data Type = Logo](https://trello.com/c/DyXA8RBU/553-structured-data-type-logo)

2023-03-23 15:10 UTC, zarathustra323 requested changes
What, ultimately, is being changed to the company data? In other words, what's the diff between the structured data before and after?

2023-03-23 15:42 UTC, Shinsina commented
> What, ultimately, is being changed to the company data? In other words, what's the diff between the structured data before and after?

Company data **would be** having the following **removed**

`datePublished
thumbnailUrl
dateModified
headline
isBasedOn
`

However in re-examining this it appears at least some of these (ex: isBasedOn and thumbnailUrl) may just be included in the incorrect location relative to where they are supposed to end up for https://schema.org/Organization. I'll relook each one of these over and see if there is a path to resolution that doesn't remove data but rather relocates it to the correct spot.

2023-04-10 15:12 UTC, solocommand approved these changes

2023-04-10 15:12 UTC, merged