Support for image metadata on section pages
parameter1/base-cms pull request #660
Opened 2023-03-21 20:14 UTC by Shinsina

![Screenshot from 2023-03-21 15-12-51](https://user-images.githubusercontent.com/46794001/226730084-2a019a8c-f9d6-46fe-a1f3-1d59dc82ee5a.png)

2023-03-21 20:15 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [SHM - client comments on social previews rendering properly](https://trello.com/c/oPD5bNpc/433-shm-client-comments-on-social-previews-rendering-properly)

2023-03-23 13:31 UTC, zarathustra323 requested changes

2023-03-23 13:31 UTC, zarathustra323 commented on packages/marko-web/components/page/metadata/components/common.marko
> +    <meta name="image-width" property="og:image:width" item-prop="image-width" content=imageDimensions.width />
The `name` and `item-prop` attributes can be dropped from these elements

2023-03-23 13:31 UTC, zarathustra323 commented on packages/marko-web/components/page/metadata/components/common.marko
> +  <if(imageDimensions)>
This check should also include the width and height, since when `imageDimensions` is an object and it will always return truthy, even if a width or height is missing...

```marko
<if(imageDimensions && imageDimensions.width && imageDimensions.height)>
```

2023-03-23 14:39 UTC, zarathustra323 requested changes

2023-03-23 14:39 UTC, zarathustra323 commented on packages/marko-web/components/page/metadata/components/common.marko
> +    <meta property="og:image:width" content=imageDimensions.width />
The width and height values should also be stringified, so:
```marko
content=`${imageDimensions.height}`
```

Once complete can you also update the screenshot in the PR? Thanks!

2023-03-23 15:06 UTC, zarathustra323 approved these changes

2023-03-23 15:06 UTC, merged