Use `autocomplete.phrase` when phrase is detected.
parameter1/base-cms pull request #678
Opened 2023-04-13 18:27 UTC by Shinsina

This is not an end all be all "magic silver bullet" regarding search however this at the very least better lines up the entered phrase (when detected) with the returned results.

PRODUCTION:
![Screenshot from 2023-04-13 13-17-48](https://user-images.githubusercontent.com/46794001/231849677-de204924-39a2-4ab1-a85b-d06a7a4da5e1.png)

DEVELOPMENT:
![Screenshot from 2023-04-13 13-17-00](https://user-images.githubusercontent.com/46794001/231849867-f918a9de-8b1e-4bcf-9dae-82657296d1b0.png)

We may however want to investigate how "boosts", sorts, etc. are applied in either case (see: https://github.com/parameter1/base-browse/blob/main/api/src/graphql/search-content.js#L234)

2023-04-13 18:28 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Search: Enable Exact Phrase Search](https://trello.com/c/3VXxkC6f/451-search-enable-exact-phrase-search)

2023-04-13 19:56 UTC, B77Mills commented on packages/marko-web-search/loaders/search.js
> +  const phrase = (searchQuery.match(/^".+"$/) || searchQuery.match(/^'.+'$/)) ? searchQuery : '';
@Shinsina I believe you will also want to strip the wrapping quotes before setting searchQuery here. 
something like 
```markoJs
const phrase = (searchQuery.match(/^".+"$/) || searchQuery.match(/^'.+'$/)) ? searchQuery.replace(/^["'](.+(?=["']$))["']$/, '$1') : '';
```

2023-04-20 14:58 UTC, solocommand requested changes
@Shinsina Change this to use `useAutocomplete` as the parameter instead of `enableNewSearch`, as that's more descriptive of what is actually happening here.

2023-04-21 13:41 UTC, solocommand requested changes

2023-04-21 13:41 UTC, solocommand commented on packages/marko-web-search/components/query.marko
> +  useAutocomplete: site.get('useAutocomplete', false),
One more change, key this under `search`:
```suggestion
  useAutocomplete: site.get('search.useAutocomplete', false),
```

2023-04-21 13:45 UTC, merged