Use simple search when configured by site
parameter1/base-cms pull request #716
Opened 2023-06-06 15:19 UTC by Shinsina

**REQUIRES https://github.com/parameter1/base-browse/pull/57**

2023-06-06 18:29 UTC, solocommand requested changes
Since `useAutocomplete` is already in production, don't remove it to prevent backwards breaking behavior. Only add the new simple search

2023-06-07 15:43 UTC, zarathustra323 requested changes

2023-06-07 15:43 UTC, zarathustra323 commented on packages/marko-web-search/components/query.marko
> +  useMatchPhrase: site.get('search.useMatchPhrase', false),
`searchType: site.get('search.searchType'),`

2023-06-07 15:43 UTC, zarathustra323 commented on packages/marko-web-search/loaders/search.js
>      ...((assignedToWebsiteSiteIds.length || assignedToWebsiteSectionIds.length) && {
`...(searchQuery && { search: { query: searchQuery, type: searchType } }),`

2023-06-07 15:43 UTC, zarathustra323 commented on packages/marko-web-search/loaders/search.js
> +  useMatchPhrase = false,
`searchType,`

2023-06-07 15:56 UTC, zarathustra323 approved these changes

2023-06-07 15:56 UTC, merged

2023-06-07 17:29 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Search: Enable Exact Phrase Search](https://trello.com/c/3VXxkC6f/451-search-enable-exact-phrase-search)