Add getGTMUserData() & gtmUserFields prop to identityX config.
parameter1/base-cms pull request #803
Opened 2023-09-27 16:13 UTC by B77Mills

You can no configure gtm key value data pairs. At the site configuation level you can set:
```
gtmUserFields: {
    primary_role: '62b3193c39347cb0d3864305',
    job_title: '62b32c2f39347c47cd86433c',
    daily_enl: '62b330936ca6068d0407dd18',
  },
  ```
  
  This will then use this gtmUserFields object and the new function to generate a data object.  This is then sent to gtm and has the users answers mapped  by the related objectId. something looking like 

<img width="820" alt="Screen Shot 2023-09-27 at 11 15 40 AM" src="https://github.com/parameter1/base-cms/assets/3845869/6f95a8ab-766f-4a80-8a96-b767b19fddff">

2023-09-27 17:23 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add user custom questions label/answer to GTM dataLayer push when idX user exists.](https://trello.com/c/2rUezs0v/236-add-user-custom-questions-label-answer-to-gtm-datalayer-push-when-idx-user-exists)

2023-09-27 17:27 UTC, brandonbk requested changes

2023-09-27 17:27 UTC, brandonbk commented on packages/marko-web-identity-x/config.js
> +  getGTMUserFieldsData(user) {
getGTMUserData

2023-09-28 18:34 UTC, brandonbk approved these changes

2023-09-28 18:35 UTC, merged