Change to the other items on leaders page mundo
parameter1/base-cms pull request #83
Opened 2021-05-21 13:35 UTC by Shinsina

2021-05-21 14:16 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to solve for Mundo Leaders entries in Spanish and English](https://trello.com/c/oKzezqPm/50-how-to-solve-for-mundo-leaders-entries-in-spanish-and-english)

2021-05-21 14:24 UTC, Shinsina commented
Build fails as this relies on change found in https://github.com/parameter1/pmmi-media-group-websites/pull/212 (I believe)

2021-05-26 15:22 UTC, solocommand requested changes

2021-05-26 15:22 UTC, solocommand commented on packages/marko-web-theme-default/components/content/contact-details/index.marko
> +          <span class=`${blockName}__label`>${i18n(lang, 'phoneLabel')}:</span>
Use double quotes instead of single quotes in template files

2021-05-26 15:35 UTC, solocommand requested changes

2021-05-26 15:35 UTC, solocommand commented on packages/marko-web-theme-default/components/content/contact-details/index.marko
> +$ const lang = input.lang || 'en'
This one too

2021-05-26 15:36 UTC, zarathustra323 requested changes

2021-05-26 15:36 UTC, zarathustra323 commented on packages/marko-web-theme-default/i18n.js
> +export default function i18n(lang, fieldLabelKey) {
This should use CommonJS modules (e.g. `module.exports`) not ESM (`export default`)

2021-05-26 18:31 UTC, solocommand approved these changes

2021-05-26 18:31 UTC, merged