Initial P1 event content body scroll depth.
parameter1/base-cms pull request #844
Opened 2024-01-09 19:38 UTC by B77Mills

At the moment it will only track and fire on content body pages.  We will have to determine how to define the html wrapper we want to target.  For content body i am using `.page-contents__content-body` as the selector, but I'm guessing this target will need to be set per layout implementations.  

It is also only firing console logs at the moment vs firing to the p1 event collection.  
![Screenshot 2024-01-09 at 1 35 04 PM](https://github.com/parameter1/base-cms/assets/3845869/6913207d-bcc3-4838-bce8-a25ac4e639a6)

2024-01-16 14:40 UTC, brandonbk requested changes, later dismissed

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/components/marko.json
> +  "<marko-web-p1-events-track-page-view-depth>": {
Rename to `marko-web-p1-events-track-scroll-depth`

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/components/track-page-view-depth.marko
> +<marko-web-browser-component
Rename to `P1EventsTrackScrollDepth` and rename file

2024-01-16 14:40 UTC, brandonbk commented on services/example-website/server/templates/content.marko
> +            <marko-web-p1-events-track-page-view-depth obj={id: content.id, type: content.type } />
Rename to `marko-web-p1-events-track-scroll-depth`

2024-01-16 14:40 UTC, brandonbk commented on services/example-website/server/templates/index.marko
> +    <marko-web-p1-events-track-page-view-depth obj={ id: 'home', type: 'section' } selector=".document-container" />
Rename to `marko-web-p1-events-track-scroll-depth`

2024-01-16 14:40 UTC, brandonbk commented on services/example-website/server/templates/section.marko
> +    <marko-web-p1-events-track-page-view-depth obj={ id: section.id, type: 'Section' } selector=".document-container" />
Rename to `marko-web-p1-events-track-scroll-depth`

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/components/marko.json
> +    "template": "./track-page-view-depth.marko",
Update reference when file is renamed

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/browser/track-page-view-depth.vue
> +      default: () => ([0.25, 0.50, 0.75]),
Add 0.90 to list of default depths

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/browser/index.js
> +  Browser.register('P1EventsTrackPageViewDepth', TrackPageViewDepth);
Rename to `P1EventsTrackScrollDepth`

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/browser/track-page-view-depth.vue
> +      default: '.document-container .page .row .content-page-body',
Remove the default and make the selector required

2024-01-16 14:40 UTC, brandonbk commented on packages/marko-web-p1-events/browser/track-page-view-depth.vue
> +    action: {
Remove this since it is generated

2024-01-17 16:56 UTC, solocommand requested changes

2024-01-17 16:56 UTC, solocommand commented on packages/marko-web-p1-events/components/track-scroll-depth/content.marko
> +  category = 'Content',
Don't allow action or category to be customized in the specific components -- content should always be content category and action should always be scroll.

The category should be required on your generic/static component, but action should still be hardcoded to scroll.

2024-01-22 19:23 UTC, solocommand approved these changes

2024-01-22 19:24 UTC, merged

2024-01-22 19:26 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Inbody Scroll depth tracking](https://trello.com/c/YFoNcGcU/242-inbody-scroll-depth-tracking)