Set unpublished $gt now
parameter1/base-cms pull request #93
Opened 2021-06-01 21:24 UTC by B77Mills

It was using since if set, but it should always use now. Content can be queried with publishedDate between two dates, but unpublished should always be before now.

2021-06-01 21:48 UTC, solocommand requested changes

2021-06-01 21:48 UTC, solocommand commented on packages/utils/src/get-published-content-criteria.js
> +          { unpublished: { $gt: now } },
I don't think this is correct behavior. With this change, you can no longer use the `since` parameter since the `date` var is no longer used for the unpublished date bound.

You'll need to find a balance here that allows the user to specify the unpublished date, rather than defaulting to `now`. Perhaps chaining an `$and` if `since` exists?

2021-06-02 03:02 UTC, zarathustra323 commented on packages/utils/src/get-published-content-criteria.js
> +          { unpublished: { $gt: now } },
I disagree (I think)... the intent is to prevent expired from content from showing... ever. It is an `allPublishedContent` operation, after all. :)

2021-06-02 03:04 UTC, zarathustra323 commented on packages/utils/src/get-published-content-criteria.js
> +          { unpublished: { $gt: now } },
How would you envision using an `$and` when `since` is present? An and with `now`? That would result in the exact same query result

2021-06-02 19:20 UTC, zarathustra323 approved these changes

2021-06-02 19:20 UTC, merged