Add monorail `theme-facebook-connect` component
parameter1/base-cms pull request #939
Opened 2024-08-02 20:08 UTC by B77Mills

This will be used to replace these once released 

https://github.com/parameter1/transpire-media-websites/pull/1/files/ac4fe0ea022528e16895dd989cd628f34aeeff7d#diff-1afebdf09957f4376786719a272ea3b8a2c30da70411f813e3653719997359b9

&&

https://github.com/parameter1/bobit-business-media-websites/blob/master/packages/global/components/facebook-connect.marko

2024-08-02 20:14 UTC, solocommand requested changes

2024-08-02 20:14 UTC, solocommand commented on packages/marko-web-theme-monorail/components/marko.json
> +    "template": "./facebook-connect.marko"
This should accept an ids prop:
```suggestion
    "template": "./facebook-connect.marko",
    "@ids": "array"
```

2024-08-02 20:14 UTC, solocommand commented on packages/marko-web-theme-monorail/components/facebook-connect.marko
> +  $ const { ids } = facebookConnect;
This should read the ids from the input, not from the site config:

```suggestion
import { getAsArray } from "@parameter1/base-cms-object-path";
$ const ids = getAsArray(input, "ids");

<if(ids.length)>
```

2024-08-05 13:01 UTC, brandonbk approved these changes

2024-08-05 13:01 UTC, merged